apiVersion: v1
kind: Service
metadata:
  name: app-canary
  labels:
    {{- include "poc-argorollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "poc-argorollout.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: app-stable
  labels:
    {{- include "poc-argorollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "poc-argorollout.selectorLabels" . | nindent 4 }}
